import {useEffect,useMemo,useRef,useState} from 'react';
import type {KeyboardEvent} from 'react';
import type {DocumentItem,Version} from '../services/api';
import {clearDraft,preserveDraft,recoverDraft,saveWithDraftFallback} from './editorPersistence';

export type SaveState='saved'|'dirty'|'saving'|'conflict'|'error';
const escapeHtml=(value:string)=>value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');

function sanitizeHtml(html:string){
  const template=window.document.createElement('template'); template.innerHTML=html;
  template.content.querySelectorAll('script,iframe,object,embed,form,style,link,meta').forEach(node=>node.remove());
  template.content.querySelectorAll('*').forEach(node=>[...node.attributes].forEach(attr=>{
    const name=attr.name.toLowerCase(),value=attr.value.trim().toLowerCase();
    if(name.startsWith('on')||name==='srcdoc'||((name==='href'||name==='src')&&(value.startsWith('javascript:')||value.startsWith('data:')))) node.removeAttribute(attr.name);
  }));
  return template.innerHTML;
}
export function markdownToHtml(source:string){
  const raw=(source||'').trim();
  if(/<\s*(p|div|h[1-6]|ul|ol|table|blockquote|section|article)\b/i.test(raw)) return sanitizeHtml(source);
  const safe=escapeHtml(source||'').replace(/\r\n/g,'\n'),lines=safe.split('\n'); let html='',inUl=false,inOl=false;
  const close=()=>{if(inUl){html+='</ul>';inUl=false}if(inOl){html+='</ol>';inOl=false}};
  for(let i=0;i<lines.length;i++){const line=lines[i];
    if(/^\s*\|.+\|$/.test(line)&&/^\s*\|?\s*:?-{3,}:?\s*\|/.test(lines[i+1]||'')){close();const header=parseTableRow(line);i++;const rows:string[][]=[];while(i+1<lines.length&&/^\s*\|.+\|$/.test(lines[i+1])&&!/^\s*\|?\s*:?-{3,}:?\s*\|/.test(lines[i+1])){i++;rows.push(parseTableRow(lines[i]))}html+='<table><thead><tr>'+header.map(c=>'<th>'+inline(c)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+inline(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';continue}
    if(/^\s*[-*]\s+/.test(line)){if(!inUl){close();html+='<ul>';inUl=true}html+='<li>'+inline(line.replace(/^\s*[-*]\s+/,''))+'</li>';continue}
    if(/^\s*\d+[.)]\s+/.test(line)){if(!inOl){close();html+='<ol>';inOl=true}html+='<li>'+inline(line.replace(/^\s*\d+[.)]\s+/,''))+'</li>';continue}
    close();if(!line.trim()){html+='<p><br></p>';continue}
    if(/^###\s+/.test(line)){html+='<h3>'+inline(line.replace(/^###\s+/,''))+'</h3>';continue}
    if(/^##\s+/.test(line)){html+='<h2>'+inline(line.replace(/^##\s+/,''))+'</h2>';continue}
    if(/^#\s+/.test(line)){html+='<h1>'+inline(line.replace(/^#\s+/,''))+'</h1>';continue}
    if(/^>\s+/.test(line)){html+='<blockquote>'+inline(line.replace(/^>\s+/,''))+'</blockquote>';continue}
    html+='<p>'+inline(line)+'</p>';
  } close();return html||'<p><br></p>';
}
function parseTableRow(line:string){return line.trim().replace(/^\|/,'').replace(/\|$/,'').split('|').map(c=>c.trim())}
function inline(value:string){
  const codes:string[]=[];let text=value.replace(/\x60([^\x60]+)\x60/g,(_,code)=>{const key=String.fromCharCode(0)+codes.length+String.fromCharCode(0);codes.push('<code>'+code+'</code>');return key});
  text=text.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/__([^_]+)__/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/_([^_]+)_/g,'<em>$1</em>').replace(/~~([^~]+)~~/g,'<s>$1</s>');
  codes.forEach((code,i)=>{text=text.replace(String.fromCharCode(0)+i+String.fromCharCode(0),code)});return text;
}

type LocalFile={file:File;path:string;editable:boolean};type Tool={cmd:string;icon:string;label:string;title:string};
export function Editor({document,versions,onSave,onClose,onConflict}:{document:DocumentItem;versions:Version[];onSave:(data:{name:string;document_type:string;content:string;base_version_id:string|null})=>Promise<'saved'|'conflict'>;onClose:()=>void;onConflict:()=>Promise<DocumentItem>}){
  const initial=document.content||'';const[name,setName]=useState(document.name),[type,setType]=useState(document.document_type),[content,setContent]=useState(initial),[state,setState]=useState<SaveState>('saved'),[message,setMessage]=useState('Salvo'),[readOnly,setReadOnly]=useState(false),[zoom,setZoom]=useState(100),[wordCount,setWordCount]=useState(0),[localFiles,setLocalFiles]=useState<LocalFile[]>([]),[selectedLocalPath,setSelectedLocalPath]=useState(''),[folderName,setFolderName]=useState(''),[fileError,setFileError]=useState(''),[format,setFormat]=useState('Normal'),[fontSize,setFontSize]=useState('16px'),[fontFamily,setFontFamily]=useState('Arial');
  const fileInputRef=useRef<HTMLInputElement>(null),editorRef=useRef<HTMLDivElement>(null),history=useRef<string[]>([initial]),future=useRef<string[]>([]),timer=useRef<number|undefined>(undefined),lastHtml=useRef('');
  const draft=useMemo(()=>{try{return recoverDraft(localStorage,document.id)}catch{return null}},[document.id]);
  useEffect(()=>{setName(document.name);setType(document.document_type);setContent(document.content||'');setState('saved');setMessage('Salvo');history.current=[document.content||''];future.current=[];setFormat('Normal');setZoom(100)},[document.id]);
  useEffect(()=>{if(editorRef.current){const html=markdownToHtml(document.content||'');editorRef.current.innerHTML=html;lastHtml.current=sanitizeHtml(html)}},[document.id]);
  useEffect(()=>{if(draft!==null&&draft!==initial){setContent(draft);setState('dirty');setMessage('Rascunho local recuperado');if(editorRef.current){const html=markdownToHtml(draft);editorRef.current.innerHTML=html;lastHtml.current=sanitizeHtml(html)}}},[draft,initial]);
  useEffect(()=>{const f=()=>{if(state!=='saved')try{preserveDraft(localStorage,document.id,content)}catch{}};window.addEventListener('visibilitychange',f);return()=>window.removeEventListener('visibilitychange',f)},[content,state,document.id]);
  useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(['dirty','saving','conflict'].includes(state)){e.preventDefault();e.returnValue=true}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[state]);
  useEffect(()=>()=>{if(timer.current)window.clearTimeout(timer.current)},[]);
  useEffect(()=>{const t=(editorRef.current?.innerText||'').trim();setWordCount(t?t.split(/\s+/).length:0)},[content]);

  function syncEditor(){if(!editorRef.current)return;const html=sanitizeHtml(editorRef.current.innerHTML);if(html===lastHtml.current)return;lastHtml.current=html;setContent(html);setState('dirty');setMessage('Alterações não salvas');if(history.current[history.current.length-1]!==html){history.current.push(html);if(history.current.length>100)history.current.shift()}future.current=[]}
  function focusEditor(){editorRef.current?.focus()}
  function exec(command:string,value?:string){if(readOnly)return;focusEditor();window.document.execCommand(command,false,value);syncEditor()}
  function formatBlock(tag:string){if(readOnly)return;focusEditor();window.document.execCommand('formatBlock',false,tag);setFormat(tag==='h1'?'Título 1':tag==='h2'?'Título 2':tag==='h3'?'Título 3':tag==='blockquote'?'Citação':'Normal');syncEditor()}
  function insertLink(){const url=window.prompt('Endereço do link:','https://');if(url)exec('createLink',url)}
  function insertImage(){const url=window.prompt('URL da imagem:','https://');if(url)exec('insertImage',url)}
  function insertTable(){if(readOnly)return;const rows=Math.max(1,Number(window.prompt('Número de linhas:','3'))||3),cols=Math.max(1,Number(window.prompt('Número de colunas:','3'))||3);let html='<table><tbody>';for(let r=0;r<rows;r++){html+='<tr>';for(let c=0;c<cols;c++)html+=(r===0?'<th>Cabeçalho</th>':'<td>Texto</td>');html+='</tr>'}html+='</tbody></table><p><br></p>';focusEditor();window.document.execCommand('insertHTML',false,html);syncEditor()}
  function setColor(command:'foreColor'|'hiliteColor'){const color=window.prompt(command==='foreColor'?'Cor do texto (ex.: #6d7cff)':'Cor de destaque (ex.: #fff2a8)',command==='foreColor'?'#6d7cff':'#fff2a8');if(color)exec(command,color)}
  function changeFontSize(size:string){setFontSize(size);exec('fontSize',size==='12px'?'2':size==='14px'?'3':size==='18px'?'4':size==='24px'?'5':'6')}
  function change(next:string){if(!editorRef.current)return;const html=markdownToHtml(next);editorRef.current.innerHTML=html;lastHtml.current=sanitizeHtml(html);setContent(lastHtml.current);setState('dirty');setMessage('Alterações não salvas');history.current.push(lastHtml.current);future.current=[]}
  function undo(){if(history.current.length<2)return;const current=history.current.pop()!;future.current.push(current);const next=history.current[history.current.length-1];if(editorRef.current)editorRef.current.innerHTML=sanitizeHtml(markdownToHtml(next));lastHtml.current=next;setContent(next);setState('dirty');setMessage('Alterações não salvas')}
  function redo(){const next=future.current.pop();if(!next)return;history.current.push(next);if(editorRef.current)editorRef.current.innerHTML=sanitizeHtml(markdownToHtml(next));lastHtml.current=next;setContent(next);setState('dirty');setMessage('Alterações não salvas')}
  async function save(){if(readOnly||state==='saving')return;const html=sanitizeHtml(editorRef.current?.innerHTML||content);setContent(html);setState('saving');setMessage('Salvando…');try{const result=await saveWithDraftFallback(localStorage,document.id,html,()=>onSave({name,document_type:type,content:html,base_version_id:document.current_version_id}),r=>r==='saved');if(result==='conflict'){setState('conflict');setMessage('Conflito: o documento foi alterado em outra sessão');return}history.current=[html];future.current=[];lastHtml.current=html;setState('saved');setMessage('Salvo agora')}catch{setState('error');setMessage('Falha ao salvar. O rascunho local foi preservado.')}}
  useEffect(()=>{if(state!=='dirty')return;if(timer.current)window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>void save(),1400)},[content,name,type]);
  async function handleFolderFiles(list:FileList|null){if(!list?.length)return;const files=Array.from(list).map(file=>({file,path:(file as File&{webkitRelativePath?:string}).webkitRelativePath||file.name,editable:/^(text\/|application\/(json|javascript|xml|yaml|x-yaml|toml|sql)|image\/svg\+xml)/.test(file.type)||/\.(txt|md|markdown|mdx|json|js|jsx|ts|tsx|css|html|htm|xml|svg|yaml|yml|toml|sql|csv|log)$/i.test(file.name)})).sort((a,b)=>a.path.localeCompare(b.path,'pt-BR'));setLocalFiles(files);setSelectedLocalPath('');setFolderName(files[0]?.path.split('/')[0]||'Pasta selecionada')}
  async function openLocalFile(item:LocalFile){setFileError('');setSelectedLocalPath(item.path);if(!item.editable){setFileError('Este formato ainda não é editável diretamente no navegador.');return}try{const text=await item.file.text();setName(item.file.name);setType(item.file.name.split('.').pop()?.toLowerCase()||'txt');change(text);focusEditor()}catch{setFileError('Não foi possível ler este arquivo.')}}
  function downloadCurrent(){const ext=(type||'html').replace(/[^a-z0-9]/gi,'')||'html';const blob=new Blob([ext==='html'?content:editorRef.current?.innerText||content],{type:ext==='html'?'text/html;charset=utf-8':'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),a=window.document.createElement('a');a.href=url;a.download=(name.replace(/\.[^.]+$/,'')||'documento')+'.'+ext;a.click();URL.revokeObjectURL(url)}
  function requestClose(){if(['dirty','saving','conflict','error'].includes(state)&&!window.confirm('Existem alterações não salvas. Deseja realmente sair?'))return;onClose()}
  function key(e:KeyboardEvent<HTMLDivElement>){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void save()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='b'){e.preventDefault();exec('bold')}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='i'){e.preventDefault();exec('italic')}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='u'){e.preventDefault();exec('underline')}}
  const tools:Tool[]=[{cmd:'undo',icon:'undo',label:'Desfazer',title:'Desfazer'},{cmd:'redo',icon:'redo',label:'Refazer',title:'Refazer'},{cmd:'bold',icon:'bold',label:'Negrito',title:'Negrito'},{cmd:'italic',icon:'italic',label:'Itálico',title:'Itálico'},{cmd:'underline',icon:'underline',label:'Sublinhado',title:'Sublinhado'},{cmd:'strikeThrough',icon:'strike',label:'Tachado',title:'Tachado'},{cmd:'insertUnorderedList',icon:'list',label:'Lista',title:'Lista com marcadores'},{cmd:'insertOrderedList',icon:'listNumber',label:'Lista numerada',title:'Lista numerada'},{cmd:'justifyLeft',icon:'alignLeft',label:'Esquerda',title:'Alinhar à esquerda'},{cmd:'justifyCenter',icon:'alignCenter',label:'Centro',title:'Centralizar'},{cmd:'justifyRight',icon:'alignRight',label:'Direita',title:'Alinhar à direita'},{cmd:'justifyFull',icon:'alignJustify',label:'Justificar',title:'Justificar'},{cmd:'outdent',icon:'outdent',label:'Recuar menos',title:'Diminuir recuo'},{cmd:'indent',icon:'indent',label:'Recuar mais',title:'Aumentar recuo'}];

  return <section className="editor-workspace">
    <header className="editor-head"><div className="editor-title-wrap"><div className="editor-breadcrumb">KORCZAK DOCUMENTS / EDIÇÃO</div><input className="editor-title" value={name} onChange={e=>{setName(e.target.value);setState('dirty');setMessage('Alterações não salvas')}}/><div className={'save-state '+state}><span className="save-dot"/>{message}{versions.length?' · v'+versions[0].version_number:''}</div></div><div className="editor-actions"><button className="editor-secondary editor-labeled" onClick={()=>setReadOnly(!readOnly)}><Icon name={readOnly?'edit':'lock'} size={15}/><span>{readOnly?'Editar':'Somente leitura'}</span></button>{state==='conflict'&&<button className="editor-secondary" onClick={async()=>{const fresh=await onConflict();try{clearDraft(localStorage,document.id)}catch{}setContent(fresh.content||'');if(editorRef.current)editorRef.current.innerHTML=markdownToHtml(fresh.content||'');setName(fresh.name);setType(fresh.document_type);history.current=[fresh.content||''];future.current=[];setState('saved');setMessage('Versão atual recarregada')}}>Recarregar versão atual</button>}<button className="editor-secondary editor-labeled" onClick={requestClose}><Icon name="close" size={15}/><span>Sair</span></button><button className="editor-save editor-labeled" disabled={state==='saving'||readOnly} onClick={()=>void save()}><Icon name="save" size={15}/><span>Salvar</span></button></div></header>
    {!readOnly&&<div className="editor-toolbar">
      <select className="editor-select" value={format} onChange={e=>formatBlock(e.target.value==='Normal'?'p':e.target.value==='Título 1'?'h1':e.target.value==='Título 2'?'h2':e.target.value==='Título 3'?'h3':'blockquote')}><option>Normal</option><option>Título 1</option><option>Título 2</option><option>Título 3</option><option>Citação</option></select>
      <select className="editor-select font-family" value={fontFamily} onChange={e=>{setFontFamily(e.target.value);exec('fontName',e.target.value)}}><option>Arial</option><option>Calibri</option><option>Georgia</option><option>Times New Roman</option><option>Verdana</option><option>Courier New</option></select>
      <select className="editor-select font-size" value={fontSize} onChange={e=>changeFontSize(e.target.value)}><option value="12px">12</option><option value="14px">14</option><option value="16px">16</option><option value="18px">18</option><option value="24px">24</option><option value="32px">32</option></select><span className="toolbar-separator"/>
      {tools.map(t=><button className="editor-tool" type="button" key={t.cmd} title={t.title} aria-label={t.title} onMouseDown={e=>e.preventDefault()} onClick={()=>t.cmd==='undo'?undo():t.cmd==='redo'?redo():exec(t.cmd)}><Icon name={t.icon} size={16}/><span>{t.label}</span></button>)}
      <span className="toolbar-separator"/><button className="editor-tool" type="button" title="Inserir link" aria-label="Inserir link" onMouseDown={e=>e.preventDefault()} onClick={insertLink}><Icon name="link" size={16}/><span>Link</span></button><button className="editor-tool" type="button" title="Inserir imagem" aria-label="Inserir imagem" onMouseDown={e=>e.preventDefault()} onClick={insertImage}><Icon name="image" size={16}/><span>Imagem</span></button><button className="editor-tool" type="button" title="Inserir tabela" aria-label="Inserir tabela" onMouseDown={e=>e.preventDefault()} onClick={insertTable}><Icon name="table" size={16}/><span>Tabela</span></button><button className="editor-tool" type="button" title="Linha horizontal" aria-label="Linha horizontal" onMouseDown={e=>e.preventDefault()} onClick={()=>exec('insertHorizontalRule')}><Icon name="horizontalRule" size={16}/><span>Linha</span></button><button className="editor-tool" type="button" title="Cor do texto" aria-label="Cor do texto" onMouseDown={e=>e.preventDefault()} onClick={()=>setColor('foreColor')}><Icon name="textColor" size={16}/><span>Cor</span></button><button className="editor-tool" type="button" title="Realce" aria-label="Realce" onMouseDown={e=>e.preventDefault()} onClick={()=>setColor('hiliteColor')}><Icon name="highlight" size={16}/><span>Realce</span></button><button className="editor-tool" type="button" title="Limpar formatação" aria-label="Limpar formatação" onMouseDown={e=>e.preventDefault()} onClick={()=>exec('removeFormat')}><Icon name="clearFormat" size={16}/><span>Limpar</span></button>
    </div>}
    <div className="editor-info"><span>{type.toUpperCase()}</span><span>{wordCount.toLocaleString('pt-BR')} palavras</span><span>{content.length.toLocaleString('pt-BR')} caracteres</span><div className="editor-zoom"><span className="editor-zoom-label"><Icon name="zoom" size={14}/><span>Zoom</span></span><button aria-label="Diminuir zoom" title="Diminuir zoom" onClick={()=>setZoom(z=>Math.max(70,z-10))}><Icon name="minus" size={14}/></button><span>{zoom}%</span><button aria-label="Aumentar zoom" title="Aumentar zoom" onClick={()=>setZoom(z=>Math.min(150,z+10))}><Icon name="plus" size={14}/></button></div></div>
    <div className="editor-body rich-editor-body">
      <input ref={fileInputRef} type="file" multiple style={{display:'none'}} onChange={e=>void handleFolderFiles(e.target.files)} {...({webkitdirectory:'',directory:''} as React.InputHTMLAttributes<HTMLInputElement>)}/>
      <div className="editor-canvas"><div className="editor-page" style={{transform:'scale('+zoom/100+')',transformOrigin:'top center',marginBottom:((1-zoom/100)*-100)+'%'}}><div ref={editorRef} className="rich-editor" contentEditable={!readOnly} suppressContentEditableWarning onInput={syncEditor} onKeyDown={key} onBlur={syncEditor} spellCheck aria-label="Editor de documento"/></div></div>
      <aside className="editor-side"><div className="editor-files-head"><strong>Arquivos</strong><button type="button" className="editor-file-action editor-labeled" onClick={()=>fileInputRef.current?.click()}><Icon name="folderOpen" size={15}/><span>Selecionar pasta</span></button></div>{folderName&&<div className="editor-folder-name" title={folderName}><Icon name="folderOpen" size={16}/><span>{folderName}</span><button type="button" onClick={()=>{setLocalFiles([]);setFolderName('');setSelectedLocalPath('');setFileError('')}}>×</button></div>}{fileError&&<div className="editor-file-error">{fileError}</div>}{localFiles.length>0&&<div className="editor-file-list">{localFiles.map(item=><button type="button" key={item.path} className={'editor-file-item '+(selectedLocalPath===item.path?'active':'')} onClick={()=>void openLocalFile(item)}><span><Icon name={item.editable?'file':'lock'} size={15}/></span><span>{item.path}</span></button>)}</div>}{!localFiles.length&&<div className="editor-files-empty">Selecione uma pasta para navegar pelos arquivos locais.</div>}<div className="editor-side-divider"/><strong>Documento</strong><label>Tipo<select value={type} onChange={e=>{setType(e.target.value);setState('dirty')}} disabled={readOnly}><option value="txt">Texto</option><option value="md">Markdown</option><option value="html">HTML</option><option value="doc">Documento</option></select></label><div><span>Versão atual</span><strong>{versions[0]?.version_number||'1'}</strong></div><div><span>Última alteração</span><strong>{new Date(document.updated_at).toLocaleString('pt-BR')}</strong></div><div><span>Proteção</span><strong>Rascunho local ativo</strong></div></aside>
    </div>
    <footer className="editor-foot"><span>Ctrl/Cmd+B, I, U · Ctrl/Cmd+Z/Y · Ctrl/Cmd+S</span><div className="editor-foot-actions"><button type="button" className="editor-secondary editor-labeled" onClick={downloadCurrent}><Icon name="download" size={15}/><span>Exportar</span></button><span>{readOnly?'MODO SOMENTE LEITURA':'MODO EDIÇÃO'} · {fontFamily}</span></div></footer>
  </section>
}
