export type CloudProvider="google-drive";
type CloudSession={provider:CloudProvider;accessToken:string;refreshToken?:string;expiresAt:number;account?:string};
const KEY="kz_cloud_sessions_v2";
function read():Partial<Record<CloudProvider,CloudSession>>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return {}}}
function write(v:Partial<Record<CloudProvider,CloudSession>>){localStorage.setItem(KEY,JSON.stringify(v))}
export function getCloudSession(provider:CloudProvider){return read()[provider]||null}
export function disconnectCloud(provider:CloudProvider){const all=read();delete all[provider];write(all)}
function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
async function pkce(){const bytes=crypto.getRandomValues(new Uint8Array(32));const verifier=b64url(bytes);const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier));return{verifier,challenge:b64url(new Uint8Array(hash))}}
let runtimeClientId="";
async function clientId(){if(runtimeClientId)return runtimeClientId;const buildId=import.meta.env.VITE_GOOGLE_CLIENT_ID;if(buildId){runtimeClientId=String(buildId).trim();return runtimeClientId}try{const r=await fetch((import.meta.env.VITE_API_BASE_URL||"https://kzdoc.onrender.com")+"/api/v1/config/public");if(r.ok){const d=await r.json();runtimeClientId=String(d.google_client_id||"").trim()}}catch{}return runtimeClientId}
async function cfg(){const id=await clientId();return{clientId:id,auth:"https://accounts.google.com/o/oauth2/v2/auth",token:"https://oauth2.googleapis.com/token",scope:"openid email profile https://www.googleapis.com/auth/drive.file"}}
export async function connectCloud(){const c=await cfg();if(!c.clientId)throw new Error("Google Drive ainda não possui Client ID configurado na NexusAPI.");const{verifier,challenge}=await pkce();const state=b64url(crypto.getRandomValues(new Uint8Array(24)));sessionStorage.setItem("nexus_oauth",JSON.stringify({provider:"google-drive",state,verifier}));const url=new URL(c.auth);url.searchParams.set("client_id",c.clientId);url.searchParams.set("response_type","code");url.searchParams.set("redirect_uri",location.origin+location.pathname);url.searchParams.set("scope",c.scope);url.searchParams.set("state",state);url.searchParams.set("code_challenge",challenge);url.searchParams.set("code_challenge_method","S256");url.searchParams.set("access_type","offline");url.searchParams.set("prompt","consent");location.assign(url.toString())}
export async function finishCloudOAuth(){const q=new URLSearchParams(location.search);const code=q.get("code"),state=q.get("state");if(!code||!state)return null;let pending:null|{provider:CloudProvider;state:string;verifier:string}=null;try{pending=JSON.parse(sessionStorage.getItem("nexus_oauth")||"null")}catch{}if(!pending||pending.state!==state||pending.provider!=="google-drive")return null;const c=await cfg();if(!c.clientId)throw new Error("Google Drive ainda não possui Client ID configurado na NexusAPI.");const body=new URLSearchParams({client_id:c.clientId,grant_type:"authorization_code",code,redirect_uri:location.origin+location.pathname,code_verifier:pending.verifier});const r=await fetch(c.token,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!r.ok)throw new Error("Não foi possível concluir a autorização do Google Drive.");const data=await r.json();const session={provider:"google-drive" as const,accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+Number(data.expires_in||3600)*1000};const all=read();all["google-drive"]=session;write(all);sessionStorage.removeItem("nexus_oauth");history.replaceState({},document.title,location.pathname);await ensureRootFolder();return"google-drive" as const}
async function refresh(s:CloudSession){if(!s.refreshToken)return s;const c=await cfg();const body=new URLSearchParams({client_id:c.clientId,grant_type:"refresh_token",refresh_token:s.refreshToken});const r=await fetch(c.token,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!r.ok){disconnectCloud("google-drive");throw new Error("A autorização do Google Drive expirou. Conecte a conta novamente.")}const data=await r.json();const next={...s,accessToken:data.access_token,refreshToken:data.refresh_token||s.refreshToken,expiresAt:Date.now()+Number(data.expires_in||3600)*1000};const all=read();all["google-drive"]=next;write(all);return next}
async function request(url:string,init:RequestInit={}){let s=getCloudSession("google-drive");if(!s)throw new Error("Conecte seu Google Drive primeiro.");if(Date.now()>s.expiresAt-60000)s=await refresh(s);const h=new Headers(init.headers);h.set("Authorization","Bearer "+s.accessToken);let r=await fetch(url,{...init,headers:h});if(r.status===401&&s.refreshToken){s=await refresh(s);h.set("Authorization","Bearer "+s.accessToken);r=await fetch(url,{...init,headers:h})}if(!r.ok)throw new Error("O Google Drive recusou a operação ("+r.status+").");return r}
async function ensureRootFolder(){
  const s=getCloudSession("google-drive");
  if(!s)throw new Error("Conecte seu Google Drive primeiro.");
  if(s.rootFolderId){try{const r=await request("https://www.googleapis.com/drive/v3/files/"+encodeURIComponent(s.rootFolderId)+"?fields=id,name,mimeType,trashed");const f=await r.json();if(f.mimeType==="application/vnd.google-apps.folder"&&!f.trashed)return f}catch{}}
  const q=encodeURIComponent("name = 'Korczak Nexus' and mimeType = 'application/vnd.google-apps.folder' and trashed = false and 'root' in parents");
  const found=await request("https://www.googleapis.com/drive/v3/files?spaces=drive&pageSize=10&fields=files(id,name,mimeType,parents)&q="+q);
  const data=await found.json();
  if(data.files?.[0]){const all=read();all["google-drive"]={...s,rootFolderId:data.files[0].id};write(all);return data.files[0]}
  const created=await request("https://www.googleapis.com/drive/v3/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:"Korczak Nexus",mimeType:"application/vnd.google-apps.folder",parents:["root"]})});
  const folder=await created.json();const all=read();all["google-drive"]={...s,rootFolderId:folder.id};write(all);return folder;
}
export async function listCloudFiles(folderId?:string){
  const root=await ensureRootFolder();const parent=folderId||root.id;
  const q="'"+parent+"' in parents and trashed=false";
  const r=await request("https://www.googleapis.com/drive/v3/files?spaces=drive&pageSize=1000&fields=files(id,name,mimeType,size,modifiedTime,parents,webViewLink)&q="+encodeURIComponent(q));
  return r.json();
}
export async function createCloudFolder(name:string,parentId?:string){const r=await request("https://www.googleapis.com/drive/v3/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,mimeType:"application/vnd.google-apps.folder",...(parentId?{parents:[parentId]}:{})})});return r.json()}