export type CloudProvider="google-drive"|"onedrive";
type CloudSession={provider:CloudProvider;accessToken:string;refreshToken?:string;expiresAt:number;account?:string};
const KEY="kz_cloud_sessions_v1";
function read():Partial<Record<CloudProvider,CloudSession>>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return {}}}
function write(v:Partial<Record<CloudProvider,CloudSession>>){localStorage.setItem(KEY,JSON.stringify(v));}
export function getCloudSession(provider:CloudProvider){return read()[provider]||null}
export function disconnectCloud(provider:CloudProvider){const all=read();delete all[provider];write(all);}
function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\\+/g,"-").replace(/\\//g,"_").replace(/=+$/,"")}
async function pkce(){const bytes=crypto.getRandomValues(new Uint8Array(32));const verifier=b64url(bytes);const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier));return {verifier,challenge:b64url(new Uint8Array(hash))}}
function cfg(provider:CloudProvider){return provider==="google-drive"?{clientId:import.meta.env.VITE_GOOGLE_CLIENT_ID,auth:"https://accounts.google.com/o/oauth2/v2/auth",token:"https://oauth2.googleapis.com/token",scope:"openid email profile https://www.googleapis.com/auth/drive.file"}:{clientId:import.meta.env.VITE_ONEDRIVE_CLIENT_ID,auth:"https://login.microsoftonline.com/common/oauth2/v2.0/authorize",token:"https://login.microsoftonline.com/common/oauth2/v2.0/token",scope:"openid profile email offline_access Files.ReadWrite"}}
export async function connectCloud(provider:CloudProvider){const c=cfg(provider);if(!c.clientId)throw new Error(provider==="google-drive"?"Google Drive ainda não possui Client ID configurado.":"OneDrive ainda não possui Client ID configurado.");const {verifier,challenge}=await pkce();const state=b64url(crypto.getRandomValues(new Uint8Array(24)));sessionStorage.setItem("nexus_oauth",JSON.stringify({provider,state,verifier}));const url=new URL(c.auth);url.searchParams.set("client_id",c.clientId);url.searchParams.set("response_type","code");url.searchParams.set("redirect_uri",location.origin+location.pathname);url.searchParams.set("scope",c.scope);url.searchParams.set("state",state);url.searchParams.set("code_challenge",challenge);url.searchParams.set("code_challenge_method","S256");if(provider==="google-drive"){url.searchParams.set("access_type","offline");url.searchParams.set("prompt","consent")}location.assign(url.toString())}
export async function finishCloudOAuth(){const q=new URLSearchParams(location.search);const code=q.get("code"),state=q.get("state");if(!code||!state)return null;let pending:null|{provider:CloudProvider;state:string;verifier:string}=null;try{pending=JSON.parse(sessionStorage.getItem("nexus_oauth")||"null")}catch{}if(!pending||pending.state!==state)return null;const c=cfg(pending.provider);const body=new URLSearchParams({client_id:c.clientId,grant_type:"authorization_code",code,redirect_uri:location.origin+location.pathname,code_verifier:pending.verifier});const r=await fetch(c.token,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!r.ok)throw new Error("Não foi possível concluir a autorização do armazenamento.");const data=await r.json();const session={provider:pending.provider,accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+Number(data.expires_in||3600)*1000};const all=read();all[pending.provider]=session;write(all);sessionStorage.removeItem("nexus_oauth");history.replaceState({},document.title,location.pathname);return pending.provider}
async function refresh(provider:CloudProvider,s:CloudSession){if(!s.refreshToken)return s;const c=cfg(provider);const body=new URLSearchParams({client_id:c.clientId,grant_type:"refresh_token",refresh_token:s.refreshToken});const r=await fetch(c.token,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!r.ok){disconnectCloud(provider);throw new Error("A autorização do armazenamento expirou. Conecte a conta novamente.")}const data=await r.json();const next={...s,accessToken:data.access_token,refreshToken:data.refresh_token||s.refreshToken,expiresAt:Date.now()+Number(data.expires_in||3600)*1000};const all=read();all[provider]=next;write(all);return next}
async function request(provider:CloudProvider,url:string,init:RequestInit={}){let s=getCloudSession(provider);if(!s)throw new Error("Conecte seu armazenamento primeiro.");if(Date.now()>s.expiresAt-60000)s=await refresh(provider,s);const h=new Headers(init.headers);h.set("Authorization","Bearer "+s.accessToken);let r=await fetch(url,{...init,headers:h});if(r.status===401&&s.refreshToken){s=await refresh(provider,s);h.set("Authorization","Bearer "+s.accessToken);r=await fetch(url,{...init,headers:h})}if(!r.ok)throw new Error("O armazenamento recusou a operação ("+r.status+").");return r}
export async function listCloudFiles(provider:CloudProvider,folderId?:string){if(provider==="google-drive"){const q=folderId?"'"+folderId+"' in parents and trashed=false":"'root' in parents and trashed=false";const r=await request(provider,"https://www.googleapis.com/drive/v3/files?fields=files(id,name,mimeType,size,modifiedTime,parents,webViewLink)&q="+encodeURIComponent(q));return r.json()}const url=folderId?"https://graph.microsoft.com/v1.0/me/drive/items/"+encodeURIComponent(folderId)+"/children":"https://graph.microsoft.com/v1.0/me/drive/root/children";return (await request(provider,url)).json()}
export async function createCloudFolder(provider:CloudProvider,name:string,parentId?:string){if(provider==="google-drive"){const r=await request(provider,"https://www.googleapis.com/drive/v3/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,mimeType:"application/vnd.google-apps.folder",...(parentId?{parents:[parentId]}:{})})});return r.json()}const url=parentId?"https://graph.microsoft.com/v1.0/me/drive/items/"+encodeURIComponent(parentId)+"/children":"https://graph.microsoft.com/v1.0/me/drive/root/children";return (await request(provider,url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,folder:{},'@microsoft.graph.conflictBehavior':"rename"})})).json()}