import {app,BrowserWindow,dialog,ipcMain,Menu,shell} from "electron";import {autoUpdater} from "electron-updater";import fs from "node:fs/promises";import path from "node:path";import {fileURLToPath} from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url));const API_BASE="https://kzdoc.onrender.com";let mainWindow;
function createWindow(){mainWindow=new BrowserWindow({width:1440,height:900,minWidth:1080,minHeight:680,title:"Korczak Nexus",backgroundColor:"#07111f",show:false,webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,sandbox:true,nodeIntegration:false,spellcheck:true}});mainWindow.loadFile(path.join(__dirname,"renderer.html"));mainWindow.once("ready-to-show",()=>mainWindow.show());mainWindow.on("closed",()=>{mainWindow=null})}
function sendUpdate(status,payload={}){mainWindow?.webContents.send("nexus:update",{status,...payload})}
async function checkUpdates(){if(!app.isPackaged)return;try{autoUpdater.autoDownload=false;autoUpdater.autoInstallOnAppQuit=true;autoUpdater.on("update-available",i=>sendUpdate("available",{version:i.version}));autoUpdater.on("update-not-available",()=>sendUpdate("current"));autoUpdater.on("error",e=>sendUpdate("error",{message:e.message}));autoUpdater.on("download-progress",p=>sendUpdate("downloading",{percent:Math.round(p.percent)}));autoUpdater.on("update-downloaded",i=>sendUpdate("downloaded",{version:i.version}));await autoUpdater.checkForUpdates()}catch(e){sendUpdate("error",{message:e instanceof Error?e.message:"Falha ao verificar atualização."})}}
ipcMain.handle("desktop:api-base",()=>API_BASE);ipcMain.handle("desktop:version",()=>app.getVersion());
ipcMain.handle("desktop:open-file",async()=>{const r=await dialog.showOpenDialog(mainWindow,{properties:["openFile"],filters:[{name:"Documentos",extensions:["txt","md","html","json","csv"]},{name:"Todos os arquivos",extensions:["*"]}]});if(r.canceled||!r.filePaths[0])return null;const filePath=r.filePaths[0];return{name:path.basename(filePath),path:filePath,content:await fs.readFile(filePath,"utf8")}});
ipcMain.handle("desktop:save-file",async(_e,p)=>{const r=await dialog.showSaveDialog(mainWindow,{defaultPath:p?.name||"documento.txt",filters:[{name:"Texto",extensions:["txt"]},{name:"Markdown",extensions:["md"]},{name:"Todos os arquivos",extensions:["*"]}]});if(r.canceled||!r.filePath)return{canceled:true};await fs.writeFile(r.filePath,String(p?.content??""),"utf8");return{canceled:false,path:r.filePath}});
ipcMain.handle("desktop:show-message",async(_e,p)=>dialog.showMessageBox(mainWindow,{type:p?.type||"info",title:p?.title||"Korczak Nexus",message:p?.message||"",buttons:["OK"]}));
ipcMain.handle("desktop:open-external",async(_e,url)=>{if(typeof url!=="string"||!/^https?:\/\//i.test(url))return false;await shell.openExternal(url);return true});ipcMain.handle("desktop:install-update",()=>{autoUpdater.quitAndInstall(false,true);return true});
app.whenReady().then(()=>{Menu.setApplicationMenu(Menu.buildFromTemplate([{label:"Nexus",submenu:[{label:"Sobre o Korczak Nexus",role:"about"},{type:"separator"},{label:"Sair",role:"quit"}]},{label:"Arquivo",submenu:[{label:"Abrir arquivo local",click:()=>mainWindow?.webContents.send("desktop:open-file")},{label:"Salvar como arquivo",click:()=>mainWindow?.webContents.send("desktop:save-file")}]},{label:"Editar",submenu:[{role:"undo"},{role:"redo"},{type:"separator"},{role:"cut"},{role:"copy"},{role:"paste"},{role:"selectAll"}]},{label:"Janela",submenu:[{role:"minimize"},{role:"togglefullscreen"}]}]));createWindow();setTimeout(checkUpdates,2500);app.on("activate",()=>{if(!BrowserWindow.getAllWindows().length)createWindow()})});app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});