import {app,BrowserWindow,dialog,ipcMain,Menu,shell} from "electron";import http from "node:http";import crypto from "node:crypto";import fs from "node:fs/promises";import path from "node:path";import {fileURLToPath} from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url));const API_BASE="https://kzdoc.onrender.com";const RELEASES="https://api.github.com/repos/korczaktech/kz-nexus/releases?per_page=30";let mainWindow;let driveSession=null;let driveServer=null;

function b64url(v){return Buffer.from(v).toString("base64url")}
function pkce(){const verifier=b64url(crypto.randomBytes(32));return{verifier,challenge:b64url(crypto.createHash("sha256").update(verifier).digest())}}
async function googleClientId(){const r=await fetch(API_BASE+"/api/v1/config/public");const d=await r.json();if(!r.ok||!d.google_client_id)throw new Error("GOOGLE_CLIENT_ID não está configurado na NexusAPI.");return d.google_client_id}
async function connectDrive(){if(driveSession)return{connected:true};const clientId=await googleClientId(),{verifier,challenge}=pkce(),state=b64url(crypto.randomBytes(24));driveServer=http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://127.0.0.1");if(u.pathname!=="/oauth/callback")return res.end();if(u.searchParams.get("state")!==state)throw Error("Estado OAuth inválido.");const code=u.searchParams.get("code");if(!code)throw Error("Autorização cancelada.");const redirect="http://127.0.0.1:"+driveServer.address().port+"/oauth/callback";const body=new URLSearchParams({client_id:clientId,grant_type:"authorization_code",code,redirect_uri:redirect,code_verifier:verifier});const tr=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const d=await tr.json();if(!tr.ok)throw Error(d.error_description||"Falha na autorização.");driveSession={accessToken:d.access_token,refreshToken:d.refresh_token,expiresAt:Date.now()+Number(d.expires_in||3600)*1000};res.end("Google Drive conectado. Você pode voltar ao Nexus.");setTimeout(()=>driveServer?.close(),500);mainWindow?.webContents.send("nexus:drive-connected")}catch(e){res.statusCode=500;res.end(String(e.message||e));mainWindow?.webContents.send("nexus:drive-error",{message:String(e.message||e)})}});await new Promise((ok,bad)=>{driveServer.once("error",bad);driveServer.listen(0,"127.0.0.1",ok)});const redirect="http://127.0.0.1:"+driveServer.address().port+"/oauth/callback",u=new URL("https://accounts.google.com/o/oauth2/v2/auth");Object.entries({client_id:clientId,response_type:"code",redirect_uri:redirect,scope:"openid email profile https://www.googleapis.com/auth/drive.file",access_type:"offline",prompt:"consent",state,code_challenge:challenge,code_challenge_method:"S256"}).forEach(([k,v])=>u.searchParams.set(k,v));await shell.openExternal(u.toString());return{pending:true}}
async function driveFiles(){if(!driveSession)throw Error("Conecte o Google Drive primeiro.");const q="'root' in parents and trashed=false";const r=await fetch("https://www.googleapis.com/drive/v3/files?fields=files(id,name,mimeType,size,modifiedTime,parents,webViewLink)&q="+encodeURIComponent(q),{headers:{Authorization:"Bearer "+driveSession.accessToken}});if(!r.ok)throw Error("Google Drive recusou a consulta ("+r.status+").");return r.json()}
function createWindow(){mainWindow=new BrowserWindow({width:1440,height:900,minWidth:1080,minHeight:680,title:"Korczak Nexus",backgroundColor:"#07111f",show:false,webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,sandbox:true,nodeIntegration:false,spellcheck:true}});mainWindow.loadFile(path.join(__dirname,"renderer.html"));mainWindow.once("ready-to-show",()=>mainWindow.show());mainWindow.on("closed",()=>{mainWindow=null})}
function sendUpdate(status,payload={}){mainWindow?.webContents.send("nexus:update",{status,...payload})}
function versionParts(v){return String(v).replace(/^v/,"").split(".").map(x=>parseInt(x,10)||0)}
function newer(a,b){const x=versionParts(a),y=versionParts(b);for(let i=0;i<4;i++){if((x[i]||0)!==(y[i]||0))return(x[i]||0)>(y[i]||0)}return false}
function assetForRelease(assets){const p=process.platform;return assets.find(a=>{const n=a.name.toLowerCase();return p==="win32"?n.endsWith(".exe"):p==="darwin"?n.endsWith(".dmg"):n.endsWith(".appimage")})}
async function checkUpdates(){if(!app.isPackaged)return;try{const releases=await fetch(RELEASES,{headers:{"Accept":"application/vnd.github+json","User-Agent":"Korczak-Nexus-Desktop"}}).then(r=>r.json());const release=releases.find(x=>!x.draft&&!x.prerelease&&String(x.tag_name).startsWith("desktop-v"));if(!release)return;const current=app.getVersion();if(newer(release.tag_name.replace("desktop-v",""),current)){const asset=assetForRelease(release.assets||[]);sendUpdate("available",{version:release.tag_name.replace("desktop-v",""),url:asset?.browser_download_url||release.html_url,asset:asset?.name||""})}else sendUpdate("current")}catch(e){sendUpdate("error",{message:e instanceof Error?e.message:"Falha ao verificar atualização."})}}
ipcMain.handle("desktop:api-base",()=>API_BASE);ipcMain.handle("desktop:version",()=>app.getVersion());ipcMain.handle("desktop:drive-status",()=>({connected:!!driveSession}));ipcMain.handle("desktop:drive-connect",connectDrive);ipcMain.handle("desktop:drive-disconnect",()=>{driveSession=null;return{connected:false}});ipcMain.handle("desktop:drive-files",driveFiles);
async function readLocalFile(filePath){if(typeof filePath!=="string")return null;const resolved=path.resolve(filePath);const allowed=[".txt",".md",".markdown",".html",".htm",".json",".csv",".nexus"];if(!allowed.includes(path.extname(resolved).toLowerCase()))throw Error("Formato de arquivo não suportado pelo editor.");const stat=await fs.stat(resolved);if(!stat.isFile())throw Error("O caminho selecionado não é um arquivo.");if(stat.size>25*1024*1024)throw Error("O arquivo excede o limite de 25 MB.");return{name:path.basename(resolved),path:resolved,content:await fs.readFile(resolved,"utf8")}}
ipcMain.handle("desktop:open-file",async()=>{const r=await dialog.showOpenDialog(mainWindow,{properties:["openFile"],filters:[{name:"Documentos Nexus",extensions:["nexus","txt","md","markdown","html","htm","json","csv"]},{name:"Todos os arquivos",extensions:["*"]}]});if(r.canceled||!r.filePaths[0])return null;return readLocalFile(r.filePaths[0])});
ipcMain.handle("desktop:open-path",async(_e,filePath)=>readLocalFile(filePath));
ipcMain.handle("desktop:nexus-folder",async()=>{const folder=path.join(app.getPath("documents"),"Korczak Nexus");await fs.mkdir(folder,{recursive:true});return folder});

ipcMain.handle("desktop:save-file",async(_e,p)=>{const r=await dialog.showSaveDialog(mainWindow,{defaultPath:p?.name||"documento.txt",filters:[{name:"Texto",extensions:["txt"]},{name:"Markdown",extensions:["md"]},{name:"Todos os arquivos",extensions:["*"]}]});if(r.canceled||!r.filePath)return{canceled:true};await fs.writeFile(r.filePath,String(p?.content??""),"utf8");return{canceled:false,path:r.filePath}});
ipcMain.handle("desktop:show-message",async(_e,p)=>dialog.showMessageBox(mainWindow,{type:p?.type||"info",title:p?.title||"Korczak Nexus",message:p?.message||"",buttons:["OK"]}));
ipcMain.handle("desktop:open-nexus-folder",async()=>{const folder=path.join(app.getPath("documents"),"Korczak Nexus");await fs.mkdir(folder,{recursive:true});await shell.openPath(folder);return folder});
ipcMain.handle("desktop:open-external",async(_e,url)=>{if(typeof url!=="string"||!/^https?:\/\/(github\.com|objects\.githubusercontent\.com)/i.test(url))return false;await shell.openExternal(url);return true});
app.whenReady().then(()=>{Menu.setApplicationMenu(Menu.buildFromTemplate([{label:"Nexus",submenu:[{label:"Sobre o Korczak Nexus",role:"about"},{type:"separator"},{label:"Sair",role:"quit"}]},{label:"Arquivo",submenu:[{label:"Abrir arquivo local",click:()=>mainWindow?.webContents.send("desktop:open-file")},{label:"Salvar como arquivo",click:()=>mainWindow?.webContents.send("desktop:save-file")}]},{label:"Editar",submenu:[{role:"undo"},{role:"redo"},{type:"separator"},{role:"cut"},{role:"copy"},{role:"paste"},{role:"selectAll"}]},{label:"Janela",submenu:[{role:"minimize"},{role:"togglefullscreen"}]}]));createWindow();setTimeout(checkUpdates,2500);app.on("activate",()=>{if(!BrowserWindow.getAllWindows().length)createWindow()})});app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});