import {app,BrowserWindow,dialog,ipcMain,Menu,shell} from "electron";import fs from "node:fs/promises";import path from "node:path";import {fileURLToPath} from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url));const API_BASE="https://kzdoc.onrender.com";const RELEASES="https://api.github.com/repos/korczaktech/kz-nexus/releases?per_page=30";let mainWindow;
function createWindow(){mainWindow=new BrowserWindow({width:1440,height:900,minWidth:1080,minHeight:680,title:"Korczak Nexus",backgroundColor:"#07111f",show:false,webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,sandbox:true,nodeIntegration:false,spellcheck:true}});mainWindow.loadFile(path.join(__dirname,"renderer.html"));mainWindow.once("ready-to-show",()=>mainWindow.show());mainWindow.on("closed",()=>{mainWindow=null})}
function sendUpdate(status,payload={}){mainWindow?.webContents.send("nexus:update",{status,...payload})}
function versionParts(v){return String(v).replace(/^v/,"").split(".").map(x=>parseInt(x,10)||0)}
function newer(a,b){const x=versionParts(a),y=versionParts(b);for(let i=0;i<4;i++){if((x[i]||0)!==(y[i]||0))return(x[i]||0)>(y[i]||0)}return false}
function assetForRelease(assets){const p=process.platform;return assets.find(a=>{const n=a.name.toLowerCase();return p==="win32"?n.endsWith(".exe"):p==="darwin"?n.endsWith(".dmg"):n.endsWith(".appimage")})}
async function checkUpdates(){if(!app.isPackaged)return;try{const releases=await fetch(RELEASES,{headers:{"Accept":"application/vnd.github+json","User-Agent":"Korczak-Nexus-Desktop"}}).then(r=>r.json());const release=releases.find(x=>!x.draft&&!x.prerelease&&String(x.tag_name).startsWith("desktop-v"));if(!release)return;const current=app.getVersion();if(newer(release.tag_name.replace("desktop-v",""),current)){const asset=assetForRelease(release.assets||[]);sendUpdate("available",{version:release.tag_name.replace("desktop-v",""),url:asset?.browser_download_url||release.html_url,asset:asset?.name||""})}else sendUpdate("current")}catch(e){sendUpdate("error",{message:e instanceof Error?e.message:"Falha ao verificar atualização."})}}
ipcMain.handle("desktop:api-base",()=>API_BASE);ipcMain.handle("desktop:version",()=>app.getVersion());
ipcMain.handle("desktop:open-file",async()=>{const r=await dialog.showOpenDialog(mainWindow,{properties:["openFile"],filters:[{name:"Documentos",extensions:["txt","md","html","json","csv"]},{name:"Todos os arquivos",extensions:["*"]}]});if(r.canceled||!r.filePaths[0])return null;const filePath=r.filePaths[0];return{name:path.basename(filePath),path:filePath,content:await fs.readFile(filePath,"utf8")}});
ipcMain.handle("desktop:save-file",async(_e,p)=>{const r=await dialog.showSaveDialog(mainWindow,{defaultPath:p?.name||"documento.txt",filters:[{name:"Texto",extensions:["txt"]},{name:"Markdown",extensions:["md"]},{name:"Todos os arquivos",extensions:["*"]}]});if(r.canceled||!r.filePath)return{canceled:true};await fs.writeFile(r.filePath,String(p?.content??""),"utf8");return{canceled:false,path:r.filePath}});
ipcMain.handle("desktop:show-message",async(_e,p)=>dialog.showMessageBox(mainWindow,{type:p?.type||"info",title:p?.title||"Korczak Nexus",message:p?.message||"",buttons:["OK"]}));
ipcMain.handle("desktop:open-external",async(_e,url)=>{if(typeof url!=="string"||!/^https?:\/\/(github\.com|objects\.githubusercontent\.com)/i.test(url))return false;await shell.openExternal(url);return true});
app.whenReady().then(()=>{Menu.setApplicationMenu(Menu.buildFromTemplate([{label:"Nexus",submenu:[{label:"Sobre o Korczak Nexus",role:"about"},{type:"separator"},{label:"Sair",role:"quit"}]},{label:"Arquivo",submenu:[{label:"Abrir arquivo local",click:()=>mainWindow?.webContents.send("desktop:open-file")},{label:"Salvar como arquivo",click:()=>mainWindow?.webContents.send("desktop:save-file")}]},{label:"Editar",submenu:[{role:"undo"},{role:"redo"},{type:"separator"},{role:"cut"},{role:"copy"},{role:"paste"},{role:"selectAll"}]},{label:"Janela",submenu:[{role:"minimize"},{role:"togglefullscreen"}]}]));createWindow();setTimeout(checkUpdates,2500);app.on("activate",()=>{if(!BrowserWindow.getAllWindows().length)createWindow()})});app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});