const API=await window.nexusDesktop.apiBase();
const S={token:localStorage.getItem("nexus.desktop.token"),user:null,view:"dashboard",docs:[],folders:[],selected:null,query:""};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
async function req(path,opt={}){const h=new Headers(opt.headers);if(opt.body)h.set("Content-Type","application/json");if(S.token)h.set("Authorization","Bearer "+S.token);const r=await fetch(API+path,{...opt,headers:h});const t=await r.text();let b={};try{b=t?JSON.parse(t):{}}catch{}if(!r.ok){if(r.status===401){S.token=null;localStorage.removeItem("nexus.desktop.token");login();}throw Error(b?.error?.message||"Não foi possível concluir a operação.")}return b}
const post=(p,b)=>req(p,{method:"POST",body:JSON.stringify(b)});
function toast(m){const n=document.createElement("div");n.className="notice";n.textContent=m;document.body.append(n);setTimeout(()=>n.remove(),3000)}
function modal(title,html){document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><section><div class="row-between"><h2>'+esc(title)+'</h2><button class="iconbtn" id="mx">×</button></div>'+html+'</section></div>');$("#mx").onclick=closeModal}
function closeModal(){$("#modal")?.remove()}
async function boot(){if(!S.token)return login();try{S.user=await req("/api/v1/users/me");await refresh();render()}catch{S.token=null;localStorage.removeItem("nexus.desktop.token");login()}}
async function refresh(){[S.docs,S.folders]=await Promise.all([req("/api/v1/documents"),req("/api/v1/folders")])}
function login(){document.querySelector("#app").innerHTML='<div style="height:100vh;display:grid;place-items:center;padding:30px"><section class="card" style="width:min(440px,100%)"><div class="brand"><div class="brand-mark">N</div><div>Korczak Nexus</div></div><h1>Entrar</h1><p class="muted">Cliente Desktop independente para Windows, macOS e Linux.</p><form class="form" id="login"><input id="email" type="email" placeholder="E-mail" required><input id="pass" type="password" placeholder="Senha" required><button class="primary">Entrar</button><button type="button" class="ghost" id="reg">Criar conta</button><button type="button" class="ghost" id="rec">Recuperar acesso</button></form></section></div>';$("#login").onsubmit=async e=>{e.preventDefault();try{const s=await post("/api/v1/auth/login",{email:$("#email").value,password:$("#pass").value});S.token=s.token;localStorage.setItem("nexus.desktop.token",s.token);await boot()}catch(x){toast(x.message)}};$("#reg").onclick=register;$("#rec").onclick=recovery}
function register(){modal("Criar conta",'<form class="form" id="rf"><input id="rn" placeholder="Nome" required><input id="re" type="email" placeholder="E-mail" required><input id="rp" type="password" minlength="8" placeholder="Senha" required><button class="primary">Criar conta</button></form>');$("#rf").onsubmit=async e=>{e.preventDefault();try{const s=await post("/api/v1/auth/register",{name:$("#rn").value,email:$("#re").value,password:$("#rp").value});S.token=s.token;localStorage.setItem("nexus.desktop.token",s.token);closeModal();await boot()}catch(x){toast(x.message)}}}
function recovery(){modal("Recuperar acesso",'<form class="form" id="rcf"><input id="rc" type="email" placeholder="E-mail" required><button class="primary">Enviar</button></form>');$("#rcf").onsubmit=async e=>{e.preventDefault();try{await post("/api/v1/auth/recovery",{email:$("#rc").value});closeModal();toast("Solicitação enviada.")}catch(x){toast(x.message)}}}
function nav(id,label){return '<button class="'+(S.view===id?"active":"")+'" data-view="'+id+'">'+label+'</button>'}
function render(){document.querySelector("#app").innerHTML='<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">N</div><div>Korczak Nexus<div class="muted" style="font-size:11px">Desktop</div></div></div><nav class="nav">'+nav("dashboard","Visão geral")+nav("documents","Documentos")+nav("folders","Pastas")+nav("favorites","Favoritos")+nav("recent","Recentes")+nav("trash","Lixeira")+nav("search","Pesquisa")+nav("settings","Configurações")+'</nav><div class="bottom">'+esc(S.user?.name)+"<br>"+esc(S.user?.email)+'<br><button class="ghost" id="logout">Sair</button></div></aside><main class="main"><header class="top"><input class="search" id="global" placeholder="Pesquisar documentos..." value="'+esc(S.query)+'"><div class="top-actions"><button class="iconbtn" id="open">Abrir local</button><button class="primary" id="new">+ Novo documento</button></div></header><section class="content" id="content"></section></main></div>';$$(".nav button").forEach(b=>b.onclick=()=>{S.view=b.dataset.view;render()});$("#logout").onclick=async()=>{try{await post("/api/v1/auth/logout",{})}catch{}S.token=null;localStorage.removeItem("nexus.desktop.token");login()};$("#new").onclick=newDoc;$("#open").onclick=openLocal;$("#global").onkeydown=e=>{if(e.key==="Enter"){S.query=e.currentTarget.value;S.view="search";render()}};view()}
function table(list,trash=false){if(!list?.length)return '<div class="empty">Nenhum item encontrado.</div>';return '<table class="table"><thead><tr><th>Nome</th><th>Tipo</th><th>Atualizado</th><th>Ações</th></tr></thead><tbody>'+list.map(d=>'<tr><td><strong>'+esc(d.name)+'</strong><br><span class="muted">'+esc(d.description||"")+'</span></td><td><span class="badge">'+esc(d.document_type)+'</span></td><td>'+new Date(d.updated_at).toLocaleString("pt-BR")+'</td><td><button class="primary open" data-id="'+esc(d.id)+'">Abrir</button> '+(trash?'<button class="ghost restore" data-id="'+esc(d.id)+'">Restaurar</button>':'<button class="ghost fav" data-id="'+esc(d.id)+'">'+(d.favorite?"★":"☆")+'</button>')+'</td></tr>').join("")+'</tbody></table>'}
function bindTable(){ $$(".open").forEach(b=>b.onclick=()=>openDoc(b.dataset.id));$$(".fav").forEach(b=>b.onclick=async()=>{try{const d=S.docs.find(x=>x.id===b.dataset.id);await req("/api/v1/documents/"+encodeURIComponent(b.dataset.id)+"/favorite",{method:d?.favorite?"DELETE":"POST"});await refresh();view()}catch(x){toast(x.message)}});$$(".restore").forEach(b=>b.onclick=async()=>{try{await post("/api/v1/documents/"+encodeURIComponent(b.dataset.id)+"/restore",{});await refresh();view();toast("Documento restaurado.")}catch(x){toast(x.message)}})}
async function view(){const c=$("#content");if(S.view==="dashboard"){c.innerHTML='<div class="page-head"><div><h1>Visão geral</h1><p class="muted">Área de trabalho própria do Nexus Desktop.</p></div></div><div class="grid"><div class="card"><h3>'+S.docs.length+'</h3><span class="muted">Documentos ativos</span></div><div class="card"><h3>'+S.folders.length+'</h3><span class="muted">Pastas</span></div><div class="card"><h3>'+S.docs.filter(d=>d.favorite).length+'</h3><span class="muted">Favoritos</span></div></div><div class="card" style="margin-top:16px"><h3>Fluxo Desktop</h3><p class="muted">Crie, edite, versione, pesquise e exporte documentos sem depender da interface mobile.</p></div>';return}
if(S.view==="documents"){c.innerHTML='<div class="page-head"><div><h1>Documentos</h1><p class="muted">Documentos sincronizados com o servidor.</p></div><button class="primary" id="new2">+ Novo</button></div><div class="toolbar"><button class="ghost" id="refresh">Atualizar</button><button class="ghost" id="folder">Nova pasta</button></div>'+table(S.docs);$("#new2").onclick=newDoc;$("#refresh").onclick=async()=>{await refresh();view()};$("#folder").onclick=newFolder;bindTable();return}
if(S.view==="folders"){c.innerHTML='<div class="page-head"><div><h1>Pastas</h1><p class="muted">Organização documental.</p></div><button class="primary" id="nf">+ Nova pasta</button></div>'+ (S.folders.length?'<div class="grid">'+S.folders.map(f=>'<div class="card"><h3>📁 '+esc(f.name)+'</h3><p class="muted">'+new Date(f.updated_at).toLocaleString("pt-BR")+'</p><button class="danger del-folder" data-id="'+esc(f.id)+'">Mover para lixeira</button></div>').join("")+'</div>':'<div class="empty">Nenhuma pasta criada.</div>');$("#nf").onclick=newFolder;$$(".del-folder").forEach(b=>b.onclick=async()=>{if(!confirm("Mover esta pasta para a lixeira?"))return;try{await req("/api/v1/folders/"+b.dataset.id,{method:"DELETE"});await refresh();view()}catch(x){toast(x.message)}});return}
if(S.view==="favorites")return remote("/api/v1/favorites","Favoritos");if(S.view==="recent")return remote("/api/v1/recent","Recentes");if(S.view==="trash")return remote("/api/v1/trash","Lixeira",true);if(S.view==="search")return search(c);if(S.view==="settings")return settings(c);if(S.view==="editor")return editor(c)}
async function remote(url,title,trash=false){const c=$("#content");try{const list=await req(url);c.innerHTML='<div class="page-head"><div><h1>'+title+'</h1><p class="muted">Estado sincronizado com o Nexus.</p></div></div>'+table(list,trash);bindTable()}catch(x){c.innerHTML='<div class="empty">'+esc(x.message)+'</div>'}}
async function search(c){c.innerHTML='<div class="page-head"><div><h1>Pesquisa</h1><p class="muted">Pesquisa no servidor.</p></div></div><div class="toolbar"><input class="search" id="q" value="'+esc(S.query)+'" placeholder="Termo"><button class="primary" id="go">Pesquisar</button></div><div id="results"><div class="empty">Pesquise por nome, conteúdo ou outros critérios suportados.</div></div>';$("#go").onclick=async()=>{try{const r=await req("/api/v1/search?"+new URLSearchParams({q:$("#q").value,page:"1",page_size:"50"}));$("#results").innerHTML=table(r.items);bindTable()}catch(x){toast(x.message)}}}
async function openDoc(id){try{S.selected=await req("/api/v1/documents/"+encodeURIComponent(id));S.view="editor";render()}catch(x){toast(x.message)}}
function editor(c){const d=S.selected;c.innerHTML='<div class="page-head"><div><h1>Editor Desktop</h1><p class="muted">'+esc(d.name)+'</p></div><div class="row"><button class="ghost" id="hist">Histórico</button><button class="ghost" id="export">Exportar</button><button class="danger" id="del">Lixeira</button><button class="primary" id="save">Salvar versão</button></div></div><div class="editor"><input class="editor-title" id="title" value="'+esc(d.name)+'"><textarea class="editor-area" id="body">'+esc(d.content||"")+'</textarea></div>';$("#save").onclick=async()=>{try{const fresh=await req("/api/v1/documents/"+encodeURIComponent(d.id));const saved=await req("/api/v1/documents/"+encodeURIComponent(d.id)+"/save",{method:"POST",body:JSON.stringify({name:$("#title").value.trim()||"Sem título",document_type:d.document_type,content:$("#body").value,base_version_id:fresh.current_version_id})});S.selected=saved;await refresh();toast("Nova versão salva.")}catch(x){toast(x.message)}};$("#export").onclick=()=>window.nexusDesktop.saveFile({name:d.name+".txt",content:$("#body").value}).then(r=>{if(!r.canceled)toast("Cópia local salva.")});$("#del").onclick=async()=>{if(!confirm("Mover o documento para a lixeira?"))return;try{await req("/api/v1/documents/"+d.id,{method:"DELETE"});await refresh();S.view="documents";render()}catch(x){toast(x.message)}};$("#hist").onclick=history}
async function history(){try{const vs=await req("/api/v1/documents/"+S.selected.id+"/versions");modal("Histórico",'<div class="form">'+vs.map(v=>'<div class="card"><div class="row-between"><strong>Versão '+v.version_number+'</strong><span class="muted">'+new Date(v.created_at).toLocaleString("pt-BR")+'</span></div><button class="ghost rv" data-id="'+esc(v.id)+'">Restaurar como nova versão</button></div>').join("")+'</div>');$$(".rv").forEach(b=>b.onclick=async()=>{try{await post("/api/v1/documents/"+S.selected.id+"/versions/"+b.dataset.id+"/restore",{});closeModal();await openDoc(S.selected.id);toast("Versão restaurada.")}catch(x){toast(x.message)}})}catch(x){toast(x.message)}}
function newDoc(){modal("Novo documento",'<form class="form" id="nd"><input id="nn" placeholder="Nome" required><select id="nt"><option value="text">Texto</option><option value="markdown">Markdown</option><option value="html">HTML</option></select><textarea id="desc" placeholder="Descrição"></textarea><button class="primary">Criar documento</button></form>');$("#nd").onsubmit=async e=>{e.preventDefault();try{const d=await post("/api/v1/documents",{name:$("#nn").value.trim(),document_type:$("#nt").value,description:$("#desc").value,content:""});closeModal();await refresh();await openDoc(d.id)}catch(x){toast(x.message)}}}
function newFolder(){modal("Nova pasta",'<form class="form" id="nfo"><input id="fn" placeholder="Nome" required><button class="primary">Criar pasta</button></form>');$("#nfo").onsubmit=async e=>{e.preventDefault();try{await post("/api/v1/folders",{name:$("#fn").value.trim(),parent_id:null});closeModal();await refresh();view()}catch(x){toast(x.message)}}}
async function openLocal(){const f=await window.nexusDesktop.openFile();if(!f)return;S.selected={id:null,name:f.name,document_type:"text",content:f.content,current_version_id:null};S.view="editor";render();$("#save").textContent="Salvar localmente";$("#save").onclick=()=>window.nexusDesktop.saveFile({name:f.name,content:$("#body").value}).then(r=>{if(!r.canceled)toast("Arquivo salvo.")})}
function settings(c){c.innerHTML='<div class="page-head"><div><h1>Configurações</h1><p class="muted">Preferências e conta do cliente Desktop.</p></div></div><div class="grid"><div class="card"><h3>Conta</h3><p>'+esc(S.user.name)+'</p><p class="muted">'+esc(S.user.email)+'</p><button class="ghost" id="profile">Editar perfil</button></div><div class="card"><h3>Aplicativo</h3><p>Versão: <span id="ver">...</span></p><p class="muted">O aplicativo verifica novas versões publicadas.</p><button class="ghost" id="feedback">Enviar feedback</button></div></div>';window.nexusDesktop.version().then(v=>$("#ver").textContent=v);$("#profile").onclick=profile;$("#feedback").onclick=feedback}
function profile(){modal("Meu perfil",'<form class="form" id="pf"><input id="pn" value="'+esc(S.user.name)+'" required><input id="pp" value="'+esc(S.user.phone||"")+'" placeholder="Telefone"><button class="primary">Salvar</button></form>');$("#pf").onsubmit=async e=>{e.preventDefault();try{S.user=await req("/api/v1/users/me",{method:"PATCH",body:JSON.stringify({name:$("#pn").value,phone:$("#pp").value||null})});closeModal();render();toast("Perfil atualizado.")}catch(x){toast(x.message)}}}
function feedback(){modal("Feedback",'<form class="form" id="fb"><select id="fc"><option>bug</option><option>ideia</option><option>usabilidade</option><option>outro</option></select><textarea id="fm" required placeholder="Descreva o feedback"></textarea><button class="primary">Enviar</button></form>');$("#fb").onsubmit=async e=>{e.preventDefault();try{await post("/api/v1/feedback",{category:$("#fc").value,message:$("#fm").value});closeModal();toast("Feedback enviado.")}catch(x){toast(x.message)}}}
window.nexusDesktop.onUpdate(p=>{if(p.status==="available"&&p.url){document.body.insertAdjacentHTML("beforeend",'<div class="update" id="update"><div class="row-between"><strong>Nova versão do Nexus: '+esc(p.version)+'</strong><button class="primary" id="up">Baixar e instalar</button></div></div>');$("#up").onclick=()=>window.nexusDesktop.openExternal(p.url)}if(p.status==="downloaded")toast("Atualização baixada. Reinicie o Nexus para concluir.")});
window.nexusDesktop.onOpenFile(openLocal);window.nexusDesktop.onSaveFile(()=>{if(S.selected)window.nexusDesktop.saveFile({name:S.selected.name+".txt",content:$("#body")?.value||S.selected.content||""})});
boot();